COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:bohdan200.6@localhost:3306/newww'

production:
  <<: *common
  # В production конфігурація завантажується з AWS Secrets Manager
  # Цей рядок використовується тільки як fallback якщо AWS недоступний
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://placeholder:placeholder@localhost:3306/placeholder'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: bohdan200.6